"""add_ai_feeds_tables

Revision ID: b3aa692c4d1c
Revises: 93cfc8e97e66
Create Date: 2026-03-27 00:03:17.730544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3aa692c4d1c'
down_revision: Union[str, Sequence[str], None] = '93cfc8e97e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_feeds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('ai_config', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_feeds_org_id', 'ai_feeds', ['org_id'], unique=False)
    op.create_index('ix_ai_feeds_org_status', 'ai_feeds', ['org_id', 'status'], unique=False)
    op.create_table('ai_feed_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_feed_id', sa.Uuid(), nullable=False),
    sa.Column('article_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('entities', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('threat_level', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_feed_id'], ['ai_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_feed_results_feed_id', 'ai_feed_results', ['ai_feed_id'], unique=False)
    op.create_index('ix_ai_feed_results_published', 'ai_feed_results', ['ai_feed_id', 'published_at'], unique=False)
    op.create_table('ai_feed_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ai_feed_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('lang', sa.String(length=5), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('continent', sa.String(length=50), nullable=True),
    sa.Column('origin', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ai_feed_id'], ['ai_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_feed_sources_feed_id', 'ai_feed_sources', ['ai_feed_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_feed_sources_feed_id', table_name='ai_feed_sources')
    op.drop_table('ai_feed_sources')
    op.drop_index('ix_ai_feed_results_published', table_name='ai_feed_results')
    op.drop_index('ix_ai_feed_results_feed_id', table_name='ai_feed_results')
    op.drop_table('ai_feed_results')
    op.drop_index('ix_ai_feeds_org_status', table_name='ai_feeds')
    op.drop_index('ix_ai_feeds_org_id', table_name='ai_feeds')
    op.drop_table('ai_feeds')
    # ### end Alembic commands ###
